LOGGER_LEVEL = "INFO"

SECRET_KEY = "my_secret_key"

SQLALCHEMY_DATABASE_URI = "sqlite:////tmp/flask_blog.db"
SQLALCHEMY_ECHO = False
SQLALCHEMY_TRACK_MODIFICATIONS = False

JWT_SECRET_KEY = "superdupersecret"
REFRESH_EXP_LENGTH = 300
ACCESS_EXP_LENGTH = 100
